In [1]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive

In [2]:
import os
os.chdir("/content/gdrive/Shareddrives/LASER_on_Luhya")

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('Luhya.csv')

In [5]:
df.head()

,target_sentence,source_sentence
0,Tsino nitsio tsinzibulo tsiabakuukanyene Yesu ...,"The book of the genealogy of Jesus Christ , th..."
1,"Aburahamu yali samwana Isaka , naye Isaka yali...","Abraham begot Isaac , Isaac begot Jacob , and ..."
2,Yuda yali samwana Perezi nende Zera ne nyinabw...,"Judah begot Perez and Zerah by Tamar , Perez b..."
3,"Ramu yali , samwana Aminadabu , naye Aminadabu...","Ram begot Amminadab , Amminadab begot Nahshon ..."
4,"Salimoni yali , samwana Boazi ne nyinamwana ya...","Salmon begot Boaz by Rahab , Boaz begot Obed b..."

In [6]:
df['not_sent_tg'] = df.apply(lambda row: len(str(row.source_sentence).split('.')), axis = 1)
df['not_sent_sr'] = df.apply(lambda row: len(str(row.target_sentence).split('.')), axis = 1)

In [7]:
ab = df[df['not_sent_tg']>1]

In [15]:
ab

,target_sentence,source_sentence,not_sent_tg,not_sent_sr
1,"Aburahamu yali samwana Isaka , naye Isaka yali...","Abraham begot Isaac , Isaac begot Jacob , and ...",2,2
2,Yuda yali samwana Perezi nende Zera ne nyinabw...,"Judah begot Perez and Zerah by Tamar , Perez b...",2,2
3,"Ramu yali , samwana Aminadabu , naye Aminadabu...","Ram begot Amminadab , Amminadab begot Nahshon ...",2,2
5,Naye Yese yali samwana omuruchi Daudi . Naye D...,and Jesse begot David the king.David the king ...,3,3
6,"Solomoni yali samwana , Rehoboamu ; Rehoboamu ...","Solomon begot Rehoboam , Rehoboam begot Abijah...",2,2
...,...,...,...,...
7946,"“ Esie , Yesu erumile omumalaika wanje nobulol...","“ I , Jesus , have sent My angel to testify to...",3,3
7947,"Roho nende omweha yesi , baboola mbu , “ Yitsa...","And the Spirit and the bride say , “ Come ! ” ...",3,2
7949,Ne omundu yesi naba narusiakhwo likhuwa liosi ...,and if anyone takes away from the words of the...,2,2
7950,Ulia ourusinjia obuloli khumakhuwa kano koosi ...,"He who testifies to these things says , “ Sure...",3,2
7951,Obukoosia obwa Omwami Yesu bube khubandu ba Ny...,The grace of our Lord Jesus Christ be with you...,3,3

In [8]:
df.shape

(7952, 4)

In [9]:
bl = df[df['not_sent_tg']<=1]

In [10]:
bl

,target_sentence,source_sentence,not_sent_tg,not_sent_sr
0,Tsino nitsio tsinzibulo tsiabakuukanyene Yesu ...,"The book of the genealogy of Jesus Christ , th...",1,2
4,"Salimoni yali , samwana Boazi ne nyinamwana ya...","Salmon begot Boaz by Rahab , Boaz begot Obed b...",1,2
21,Ako koosi kekholekha khulwa okhuusia aka OMWAM...,So all this was done that it might be fulfille...,1,1
23,"Olwa Yosefu yabuukha mundoolo , yabukula Maria...","Then Joseph , being aroused from sleep , did a...",1,2
25,"Yesu yebulwa Ebuyahudi , mwitookho lia Betsele...",Now after Jesus was born in Bethlehem of Judea...,1,2
...,...,...,...,...
7895,Olwa emiyika echio eshikhumila shilala chiliba...,"Now when the thousand years have expired , Sat...",1,1
7913,"Ne mu Roho , niyambukula , niyanjinga okhumbil...",And he carried me away in the Spirit to a grea...,1,3
7915,"Liali nelisisi likhongo lirambi nende , ebilii...",Also she had a great and high wall with twelve...,1,3
7922,"Omusinji okwelisisi elielitookho , liene elo k...",The foundations of the wall of the city were a...,1,2
7948,"Isie , Yohana , esiomela buli mundu ouhulilang...",For I testify to everyone who hears the words ...,1,2

In [11]:
sent = df[df['not_sent_tg']==1]

In [12]:
sent = sent[sent['not_sent_sr']==1]

In [13]:
sent.shape

(749, 4)

In [14]:
sent

,target_sentence,source_sentence,not_sent_tg,not_sent_sr
21,Ako koosi kekholekha khulwa okhuusia aka OMWAM...,So all this was done that it might be fulfille...,1,1
29,"Nibamukalusia bari , “ Akhoyile okhwibulilwa ,...","So they said to him , “ In Bethlehem of Judea ...",1,1
41,"Mana amakhuwa akomulakusi Yeremia yaboola , ni...",Then was fulfilled what was spoken by Jeremiah...,1,1
48,"Mutsinyanga etsio , Yohana Omubatiisi yetsa na...",In those days John the Baptist came preaching ...,1,1
54,Ne olwa Yohana yalola Abafarisayo nende Abasad...,But when he saw many of the Pharisees and Sadd...,1,1
...,...,...,...,...
7861,"mana nibayula olwa balola omwosi okwetsimemu ,...",and cried out when they saw the smoke of her b...,1,1
7868,"Olunyuma olwa amakhuwa ako ndahulila eshindu ,...",After these things I heard a loud voice of a g...,1,1
7870,"Nibameeta okhwayula olwa , khabili bari , “ OM...","Again they said , “ Alleluia ! Her smoke rises...",1,1
7873,Mana nimbulila eshiahulilikha shinga amayoosi ...,"And I heard , as it were , the voice of a grea...",1,1
7895,Olwa emiyika echio eshikhumila shilala chiliba...,"Now when the thousand years have expired , Sat...",1,1

In [16]:
6116/7952

0.7691146881287726

In [18]:
a = ab.sample(n=75, random_state=1)
b = bl.sample(n=25, random_state=1)

d = pd.concat([a,b])

In [20]:
d = d[['target_sentence','source_sentence']]

In [21]:
d.to_csv('Luhya_review.csv',index=False)

In [ ]:
df2 = pd.read_csv('swahilibible.csv')

In [ ]:
df2.head()

,source_sentence,target_sentence
0,Now the Philistines fought against Israel; and...,Basi Wafilisti wakapigana juu ya Israeli; nao ...
1,And they put his armor in the house of their g...,Wakaziweka silaha zake nyumbani mwa miungu yao...
2,And when all Jabesh-gilead heard all that the ...,Na watu wote wa Yabesh-gileadi waliposikia hay...
3,"They arose, all the valiant men, and took away...","wakainuka mashujaa wote, wakautwaa mwili wake ..."
4,So Saul died for his transgression which he co...,Basi Sauli alikufa kwa sababu ya kosa lake ali...

In [ ]:
df2['not_sent_tg'] = df2.apply(lambda row: len(str(row.source_sentence).split('.')), axis = 1)
df2['not_sent_sr'] = df2.apply(lambda row: len(str(row.target_sentence).split('.')), axis = 1)

In [ ]:
df2[df2['not_sent_tg']>1]

,source_sentence,target_sentence,not_sent_tg,not_sent_sr
0,Now the Philistines fought against Israel; and...,Basi Wafilisti wakapigana juu ya Israeli; nao ...,2,2
1,And they put his armor in the house of their g...,Wakaziweka silaha zake nyumbani mwa miungu yao...,2,2
3,"They arose, all the valiant men, and took away...","wakainuka mashujaa wote, wakautwaa mwili wake ...",2,2
5,And inquired not of the LORD: therefore he sle...,"asiulize kwa Bwana; kwa hiyo akamwua, na ufalm...",2,2
6,"And the Philistines followed hard after Saul, ...",Nao Wafilisti wakamfuatia sana Sauli na wanawe...,2,2
...,...,...,...,...
31096,The just LORD is in her midst; he will do no w...,Bwana kati yake ni mwenye haki; hatatenda uovu...,2,2
31097,I have cut off the nations: their fortresses a...,"Nimekatilia mbali mataifa, buruji zao zina uki...",2,2
31098,"I said, Surely you will fear me, you will rece...","Nalisema, Hakika utaniogopa, utakubali kurudiw...",2,2
31099,"Therefore wait upon me, says the LORD, until t...","Basi ningojeni, asema Bwana, hata siku ile nit...",2,2
31100,For then will I restore to the people a pure l...,Maana hapo ndipo nitakapowarudishia mataifa lu...,2,2